### ISSUE TITLE
CLI Compile Command Returns Error

### ISSUE THREAD

**Issue by eddielao** [judepayne/dictim#15]
This might be user error.

Scenario:
Created a simple .EDN file with an empty map, {}.

File Content:
{}

In both PowerShell and Git Bash, ran the dictim CLI command, `dictim -c file.end -out file.d2`

Error: Don't know how to create ISeq from: clojure.lang.Symbol

Also tried, `dictim -c .\file.edn -o .\file.d2`

**Comment by judepayne** [comment]
Hello. Sorry it's taken me an age to get to this.

This is indeed user error (sorry!)

Because your dictim is in a file, you need the '<' symbol to tell the dictim executable to pull it in. So, the command should read.

`dictim -c < .\file.edn`

That will display the error:

`Error: no dictim to compile`

which is correct. This error will display for `{}`, `[]` and `()` i.e. all the empty collections that dictim uses.

NB, to direct output to file (including the error), use `>`

so

`dictim -c <.\file.edn > .\file.d2`

rather than the '-o' option. The `-o` option is for use with watch `-w` continuous operations. We can't use `>` on those occasions.

documentation is here: https://github.com/judepayne/dictim/wiki/Command-Line

**Comment by eddielao** [comment]
Thank you @judepayne! Sorry about the user error!
