### ISSUE TITLE
D2 file not generating

### ISSUE THREAD

**Issue by krish777** [judepayne/dictim#2]
In command line, we use dictim -a -t temp.edn -w in.d2 -o out.d2 to generate the out.d2 file. But when we remove -w i.e. without the d2 file is not generating.

Following command does not produce the out.d2 file

dictim -a -t temp.edn in.d2 -o out.d2

**Comment by judepayne** [comment]
There was a bug in the non-watch apply template code path, so the `-t` option wasn't being picked up. Fixed in v0.8.7

Also, your usage is wrong. Should be:

    dictim -a < in.d2 -t temp.edn

(to be consistent with other non-watch variants of commands like compile, parse..)
This will dump output to the terminal, so to put it in a file, add ` > out.d2` on the end, e.g.

    dictim -a < in.d2 -t temp.edn > out.d2

**Comment by krish777** [comment]
Thanks, will try it out in latest release. That was quick.
